### ISSUE TITLE
is that module still working ? 

### ISSUE THREAD

**Issue by empierre** [outadoc/linkindle#1]
2017-09-13 22:42:56,767 logging in as xxxx...
2017-09-13 22:42:56,811 Starting new HTTPS connection (1): espace-client-connexion.enedis.fr
2017-09-13 22:42:57,020 logged in successfully!
2017-09-13 22:42:57,020 retreiving data...
2017-09-13 22:42:57,023 Starting new HTTPS connection (1): espace-client-particuliers.enedis.fr
2017-09-13 22:42:59,216 Resetting dropped connection: espace-client-particuliers.enedis.fr
Traceback (most recent call last):
  File "linky_plot.py", line 230, in <module>
    main()
  File "linky_plot.py", line 203, in main
    res_year = linky.get_data_per_year(token)
  File "/home/in/domoticz-veolia-eau/linkindle/linky.py", line 70, in get_data_per_year
    return _get_data(session, 'urlCdcAn')
  File "/home/in/domoticz-veolia-eau/linkindle/linky.py", line 102, in _get_data
    return req.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Xanatos00** [comment]
Hi,
See https://github.com/Xanatos00/linkindle/commit/62d4707b6e56a76b4bde7817d00fbc3d2b14a2fb , update 2 variables

**Comment by outadoc** [comment]
Merging in PR #2 — thanks @Xanatos00 @empierre! 💯 👍
